### ISSUE TITLE
驱动报错

### ISSUE THREAD

**Issue by Xmqor** [n00b69/woa-flashlmdd#1]
最新驱动flashlmdd-drivers, 安装驱动就蓝屏报错acpi BIOS error,尝试了很多版本,未能解决,有时会报错SYSTEM THREAD BLEPTON NOT HANDLED

**Comment by Xmqor** [comment]
The latest driver Flashemund-Derrios, installing the driver on the blue screen error Appibios Ero, tried many versions, failed to solve, sometimes reported the error Sistemslade Brepton Nothandlied.This is lssue translated into English.

**Comment by Xmqor** [comment]
The latest driver, flashlmdd-drivers, reported acpi BIOS error on the blue screen when the driver was installed. Many versions were tried, but it failed to be solved, and sometimes the system thread failed to be handled.This is translated into English.

**Comment by n00b69** [comment]
Are you also using the latest UEFI?

**Comment by Xmqor** [comment]
After investigation, it was a battery drive problem, There is no problem in replacing the battery driver of redmi k20p with the same processor.

**Comment by n00b69** [comment]
This should be fixed now
